### ISSUE TITLE
Bug: Road display incomplete and Object Deviation

### ISSUE THREAD

**Issue by immmmmia** [WoodOxen/tactics2d#100]
Hello,
I encountered an issue while running the map parser. To be more specific, the output picture displayed a few mistakes after I ran test_xodr_parser() in ~/tactics2d/test/test_map_parser.py to parse my own xodr file. The output is as follows and the errors have been circled.
![111](https://github.com/WoodOxen/tactics2d/assets/148860708/3acacbda-658f-4eaf-9315-3863357455b1)
The issue that have arisen can possibly be classified into two main groups: 1. the offset of some parking spaces; 2.the incomplete display of road. I have found that the first circumstance is caused by the function load_objection(). https://github.com/WoodOxen/tactics2d/blob/792ecd0f862588c817e1557a169314d9813caa42/tactics2d/map/parser/parse_xodr.py#L362-L364 indicates that the parser only considers the case that the road’s geometry type is line, resulting in the deviation.

- OS version: Ubuntu 20.04.4 LTS
- Python version: 3.8.10

**Comment by Merealtea** [comment]
It seems like the wrong parsing process of refline and incorrect usage of object heading, we have already fixed it. Thank you for your comments!
