### ISSUE TITLE
🐛 Bug: Parsing error in OpenDrive (.xodr) parser

### ISSUE THREAD

**Issue by SCP-CN-001** [WoodOxen/tactics2d#131]
**Describe the bug**

- OS version: All
- Python version: All

**To Reproduce**
Steps to reproduce the behavior: Run the parser of OpenDrive map

**Expected behavior**
The junction is parsed and displayed correctly.

**Error Message**
Currently, the junction is not parsed, so it is also not displayed.

**Screenshots**
![20240802-153016](https://github.com/user-attachments/assets/a2907e0d-2a02-43d5-ad92-7dce3f32110e)

**Additional context**
TODO: Add a map element called Junction and use it to store the corresponding map information in OpenDrive map.

**Comment by MotacillaAlba** [comment]
Fixed
![LargeParkingLot](https://github.com/user-attachments/assets/c0d7d1e7-3fc9-4e0c-90fe-db23fd485419)
