### ISSUE TITLE
Presentation of this work?

### ISSUE THREAD

**Issue by Liuzy0908** [WoodOxen/tactics2d#33]
It looks like an amazing project. Is there a video or paper to show the work? 
My regards.

**Comment by MotacillaAlba** [comment]
I am glad you appreciate this work. The paper about tactics2d is planned to be submitted in June/July 2023. At present there remain some nice features to be implemented.

**Comment by MotacillaAlba** [comment]
The paper of this work has been submitted to [arxiv](https://arxiv.org/abs/2311.11058).

You can also find a demo of this work [here](https://tactics2d.readthedocs.io/en/dev/tutorial/interpolator_visualization/).
